### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ashu9167** [idleice/whatsapp-analyzer#2]
getting in Mac OS python 3

**Comment by empicano** [comment]
Hi, can you post the whole error message please? Makes it easier to spot the reason.

**Comment by empicano** [comment]
Closed for inactivity.

**Comment by pcuellar** [comment]
Hi. Getting this error too, MacOS 10.15.5, Python 3.8.1. Here is the whole error message:

```
Traceback (most recent call last):
  File "analyzer.py", line 480, in <module>
    members = Text.process(PATH)
  File "analyzer.py", line 134, in process
    Text.extract(prev, members, predec)
  File "analyzer.py", line 82, in extract
    2000+int(line[6:8]),
TypeError: 'NoneType' object is not subscriptable
```

**Comment by empicano** [comment]
I can reproduce this by using either an empty chat file or one where the dates and times are malformatted. Can you recheck if your chat file is formatted in the same way is specified [in the README](https://github.com/empicano/whatsapp-analyzer#instructions)?

**Comment by pcuellar** [comment]
Here is a sample after I converted the time format of the export:
07.06.20, 02:21:01 PM 
07.06.20, 02:21:05 PM
07.06.20, 02:21:58 PM 

Original looked like this:
6/4/20, 1:35 PM 
6/7/20, 2:16 PM
6/7/20, 2:17 PM

**Comment by empicano** [comment]
Looks good, if you still convert the AM/PM format into a 24 hour format, it should work. The final format should be like this (taking the first line of your example):

`07.06.20, 14:21:01: Pedro: Hello world!`

**Comment by pcuellar** [comment]
That solved it. Thanks!
